name: Run Code Coverage Check
on:
  workflow_dispatch:
  pull_request:

jobs:
  run_code_coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const { exec: execute } = require('node:child_process');

            await execute('npm run test', async (err, stdout, stderr) => {
              const message = `Output: \n\n\`\`\`${stdout}\`\`\`\n\nErrors: \n\n\`\`\`${stderr}\`\`\``;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            });

